### ISSUE TITLE
V2 Bug Tracker

### ISSUE THREAD

**Issue by ahmedsaed** [Ahmedsaed/gdsc-cert#11]
I will use this issue to track bugs and issues for v2 of the project.

- [x] Update the `handleCreateBtn` in the create component to send the value of line1 to the database.
- [x] In the preview page, update the certificate button hit box occupy the available spac.
- [x] Rename components using better names
